# Compare the projective and lens algorithms

Import the lens and projective mds packages. We will setup a dataset on RP^4 and reduce it to RP^2 using both packages (since the lens space with a Z/2 action is projective space) to see if the Lens MDS algorithm works.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import lens_mds
import projective_mds

Loading personal version of PPCA. This may not be consistent with
        the published version


In [4]:
T,n = projective_mds.circleRPn(dim=5)
D = projective_mds.graph_distance_matrix(T,k=5)
Y = projective_mds.initial_guess(T,3)

In [5]:
# Reduce the dimension using pmds
X,C,T = projective_mds.pmds(Y,D,verbosity=0)

/opt/anaconda2/envs/stiefel-testing/lib/python3.7/site-packages/autograd/tracer.py:48: RuntimeWarning: invalid value encountered in sqrt
  return f_raw(*args, **kwargs)


No change in S matrix. Stopping iterations


In [53]:
# Check that the optimal rotations match the sign matrix:
# (CURRENTLY THEY DO NOT!)
omega = lens_mds.g_action_matrix(2,3)
print(omega)
omega_true = np.array([[-1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,-1]])
print(omega_true)
S = lens_mds.optimal_rotation(Y.T,omega,2)
S_true = lens_mds.optimal_rotation(Y.T,omega_true,2)
print(np.allclose(S,S_true))
diff_mtx = (-2*S+1)-np.sign(Y@Y.T)
print(np.allclose(np.sign(Y@Y.T),-2*S+1))
print(np.linalg.norm(diff_mtx)**2)
print(np.linalg.norm(diff_mtx,axis=1)**2)

[[-1.0000000e+00  1.2246468e-16  0.0000000e+00  0.0000000e+00]
 [-1.2246468e-16 -1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -1.0000000e+00  1.2246468e-16]
 [ 0.0000000e+00  0.0000000e+00 -1.2246468e-16 -1.0000000e+00]]
[[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]
False
False
415.99999999999994
[  0.   4.   0.   0.   0.   0.   4.   0.   0.   0.   0.   0.   4.   0.
   0.   4.   0.   0.   0.   0.   0.   4.   0.   0.   0.   0.   4.   0.
   8.   0.  16.   0.   4.   0.   0.   0.   0.   0.   0.   4.   4.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   4.   8.   0.   0.   0.   0.
   4.   0.   0.   0.   0.   0.   0.   0.   4.   0.   0.   0.   4.   0.
   0.   4.   0.   0.   0.   0.   4.   4.   0.   0.   0.   0.   0.   0.
   4.   0.   0.   0.   0.   0.   0.   4.   0.   0.   0.   4.   0.   0.
   0.   0.   0.   0.   0.   4.   4.   0.   0.   0.   0.   0.   0.   4.
   0.   0.   0.   0.   0.   0.   4.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0. 

In [17]:
# Check that the janky inner product works
print(lens_mds.lens_inner_product(Y.T,omega,S))

[[1.         0.31299168 0.86855203 ... 0.03971352 0.87062992 0.01584653]
 [0.31299168 1.         0.63860307 ... 0.65845853 0.00715713 0.57635044]
 [0.86855203 0.63860307 1.         ... 0.04370846 0.53116015 0.01744059]
 ...
 [0.03971352 0.65845853 0.04370846 ... 1.         0.0717817  0.98891749]
 [0.87062992 0.00715713 0.53116015 ... 0.0717817  1.         0.02864241]
 [0.01584653 0.57635044 0.01744059 ... 0.98891749 0.02864241 1.        ]]
